# -*- coding: utf-8 -*-
"""Assignmen01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHnyb9K3LDp_YEViK_e3Fm3DzLgqUD0B
"""

Name="Khubaib"
Space=""
for i in range(0,len(Name)):
    print(Space+Name[i])
    Space=Space+" "
   
![Output1](https://user-images.githubusercontent.com/49817481/103445593-2ede6980-4c98-11eb-967d-aab9784dedf9.png)

import time
song =["Main tera, Main tera", "Main tera, Main tera", "Main tera, Main tera"] 
def lyrics(song):
  for i in song:
    time.sleep(1)
    print(i)

lyrics(song)

![Output2](https://user-images.githubusercontent.com/49817481/103445577-dc04b200-4c97-11eb-92d8-d373009d4859.png)






