# -*- coding: utf-8 -*-
"""Assignmen01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHnyb9K3LDp_YEViK_e3Fm3DzLgqUD0B
"""

Name="Khubaib"
Space=""
for i in range(0,len(Name)):
    print(Space+Name[i])
    Space=Space+" "    
    
```
![Output1](https://user-images.githubusercontent.com/49817481/103445676-4702b880-4c99-11eb-8911-001ec7a81848.png)

```


import time
song =["Main tera, Main tera", "Main tera, Main tera", "Main tera, Main tera"] 
def lyrics(song):
  for i in song:
    time.sleep(1)
    print(i)

lyrics(song)

Main tera, Main tera
Main tera, Main tera
Main tera, Main tera






