# -*- coding: utf-8 -*-
"""Assignmen01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHnyb9K3LDp_YEViK_e3Fm3DzLgqUD0B
"""

Name="Khubaib"
Space=""
for i in range(0,len(Name)):
    print(Space+Name[i])
    Space=Space+" "

import time
song =["Main tera, Main tera", "Main tera, Main tera", "Main tera, Main tera"] 
def lyrics(song):
  for i in song:
    time.sleep(1)
    print(i)

lyrics(song)





